# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grouptrip', '0003_auto_20160227_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trippreferences',
            name='budget',
            field=models.IntegerField(),
        ),
    ]
