# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grouptrip', '0004_auto_20160227_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
