# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grouptrip', '0006_auto_20160227_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trippreference',
            name='weather',
            field=models.CharField(choices=[('SUNNY', 'Sunny'), ('CLOUDY', 'Cloudy'), ('RAINY', 'Rainy'), ('SNOWY', 'Snowy'), ('ANY', 'Any')], default='ANY', max_length=6),
        ),
    ]
