# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grouptrip', '0008_auto_20160227_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trippreference',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='trippreference',
            unique_together=set([]),
        ),
    ]
